name: "Check, Test and Build Codebase"

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Codebase"
        uses: "actions/checkout@v4"

      - name: "Install nix"
        uses: "cachix/install-nix-action@v27"
        with:
          nix_path: "nixpkgs=channel:nixos-24.05"

      - name: "Use Magic Nix cache"
        uses: "DeterminateSystems/magic-nix-cache-action@v7"

      - name: "Check, Test and Build"
        run: |
          nix-shell --pure --run "cabal update --ignore-project && cabal dev-test-build"
