name: "Check, Test and Build Codebase"

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Codebase"
        uses: "actions/checkout@v4"

      - name: "Install Nix"
        uses: "DeterminateSystems/nix-installer-action@v16"

      - name: "Use Nix Cache"
        uses: "DeterminateSystems/magic-nix-cache-action@v8"

      - name: "Check, Test and Build"
        run: |
          nix-shell --pure --run "cabal update --ignore-project && cabal dev-test-build"
